pipeline:
  py36:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    repo: tataucloud/python-horovod
    registry: docker.io
    dockerfile: Dockerfile
    tags:
      - '3.6'
    build_args:
      - PYTHON_VERSION=3.6

  py37:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    repo: tataucloud/python-horovod
    registry: docker.io
    dockerfile: Dockerfile
    tags:
      - '3.7'
    build_args:
      - PYTHON_VERSION=3.7
